module.exports={
    cls:require('./cls'),
    prop:require('./prop'),
    style:require('./style'),
    pos:require('./pos'),
    request:require('./request'),
    validate:require('./validate'),
    native:require('./native'),
    iframe:require('./iframe'),
};